import type { Product, ProductCategory } from "./types";

// ------------------------------------------------------------------
// WHOLESALE MOCK CATALOG
// B2B supplier data — no retail pricing is exposed anywhere. Pricing is
// quote-based ("Wholesale Pricing Available Upon Request"). Replaced later by
// the Supabase-backed catalog API; keep the shape in sync with `Product`.
// Images are real, keyword-matched stock photos (see CardArt) until CDN
// product photography is supplied. No copyrighted card scans are hotlinked.
// ------------------------------------------------------------------

export const products: Product[] = [
  {
    id: "bb-sv-obsidian",
    slug: "obsidian-flames-booster-box-case",
    name: "Obsidian Flames Booster Box — Sealed Case",
    category: "booster-boxes",
    set: "Scarlet & Violet — Obsidian Flames",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-BB-OBF-EN",
    caseQty: "6 booster boxes / case",
    moq: 2,
    availability: "in-stock",
    stock: 240,
    art: { from: "#1f2937", to: "#dc2626", emoji: "🔥" },
    authentic: true,
    isBestSeller: true,
    popularity: 96,
    rating: 4.9,
    reviewCount: 214,
    description:
      "Factory-sealed master case of Obsidian Flames booster boxes (6 boxes per case, 36 packs per box). Sourced through authorized distribution and verified authentic. Case-break friendly, ships palletized for larger volumes.",
  },
  {
    id: "bb-sv-paldea",
    slug: "paldea-evolved-booster-box-case",
    name: "Paldea Evolved Booster Box — Sealed Case",
    category: "booster-boxes",
    set: "Scarlet & Violet — Paldea Evolved",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-BB-PAL-EN",
    caseQty: "6 booster boxes / case",
    moq: 2,
    availability: "in-stock",
    stock: 180,
    art: { from: "#065f46", to: "#10b981", emoji: "🌿" },
    authentic: true,
    isBestSeller: true,
    popularity: 88,
    rating: 4.8,
    reviewCount: 167,
    description:
      "Master case of Paldea Evolved booster boxes, sealed and authenticity-verified. Ideal for shops running singles breaks or restocking sealed inventory at volume.",
  },
  {
    id: "etb-sv-paradox",
    slug: "paradox-rift-etb-case",
    name: "Paradox Rift Elite Trainer Box — Case",
    category: "etbs",
    set: "Scarlet & Violet — Paradox Rift",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-ETB-PDX-EN",
    caseQty: "10 ETBs / case",
    moq: 1,
    availability: "in-stock",
    stock: 120,
    art: { from: "#4c1d95", to: "#7c3aed", emoji: "🌀" },
    authentic: true,
    isNew: true,
    popularity: 91,
    rating: 4.9,
    reviewCount: 132,
    description:
      "Full case of Paradox Rift Elite Trainer Boxes (10 per case). Each ETB includes 9 booster packs plus the complete accessory set. Sealed, weight-checked, and authenticity-guaranteed.",
  },
  {
    id: "etb-sv-temporal",
    slug: "temporal-forces-etb-case",
    name: "Temporal Forces Elite Trainer Box — Case",
    category: "etbs",
    set: "Scarlet & Violet — Temporal Forces",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-ETB-TMF-EN",
    caseQty: "10 ETBs / case",
    moq: 1,
    availability: "low-stock",
    stock: 32,
    art: { from: "#0c4a6e", to: "#0ea5e9", emoji: "⏳" },
    authentic: true,
    popularity: 84,
    rating: 4.7,
    reviewCount: 98,
    description:
      "Case of Temporal Forces ETBs (10 per case). Sealed and seal-verified before dispatch — a reliable restock line for retailers and resellers.",
  },
  {
    id: "pack-obsidian-display",
    slug: "obsidian-flames-booster-packs-display",
    name: "Obsidian Flames Booster Packs — Display (36ct)",
    category: "booster-packs",
    set: "Scarlet & Violet — Obsidian Flames",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-BP-OBF-36",
    caseQty: "36 packs / display",
    moq: 4,
    availability: "in-stock",
    stock: 300,
    art: { from: "#7f1d1d", to: "#f87171", emoji: "🔥" },
    authentic: true,
    popularity: 74,
    rating: 4.6,
    reviewCount: 190,
    description:
      "Sealed 36-pack displays of Obsidian Flames boosters, pulled from sealed cases and weight-verified. Perfect for pack walls and singles operations.",
  },
  {
    id: "prem-sv-upc",
    slug: "scarlet-violet-ultra-premium-collection",
    name: "Ultra Premium Collection — Master Carton",
    category: "premium-collections",
    set: "Scarlet & Violet",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-UPC-SV-EN",
    caseQty: "4 UPCs / carton",
    moq: 1,
    availability: "in-stock",
    stock: 60,
    art: { from: "#111827", to: "#fbbf24", emoji: "👑" },
    authentic: true,
    isBestSeller: true,
    popularity: 89,
    rating: 4.9,
    reviewCount: 54,
    description:
      "Master carton of Ultra Premium Collections (4 per carton). High-demand premium SKU with strong sell-through — a margin driver for retail and online shops.",
  },
  {
    id: "colbox-sv-charizard",
    slug: "charizard-ex-collection-box-case",
    name: "Charizard ex Collection Box — Case",
    category: "collection-boxes",
    set: "Scarlet & Violet",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-CB-CHZ-EN",
    caseQty: "12 boxes / case",
    moq: 1,
    availability: "in-stock",
    stock: 96,
    art: { from: "#7c2d12", to: "#f97316", emoji: "🐉" },
    authentic: true,
    isNew: true,
    popularity: 92,
    rating: 4.9,
    reviewCount: 76,
    description:
      "Case of Charizard ex Collection Boxes (12 per case). A perennial best-seller with proven gift and impulse appeal for storefronts.",
  },
  {
    id: "tin-sv-poke-ball",
    slug: "poke-ball-tin-assortment-case",
    name: "Poké Ball Tin Assortment — Case",
    category: "tins",
    set: "Scarlet & Violet",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-TIN-PB-EN",
    caseQty: "24 tins / case",
    moq: 1,
    availability: "in-stock",
    stock: 144,
    art: { from: "#991b1b", to: "#ef4444", emoji: "🔴" },
    authentic: true,
    popularity: 71,
    rating: 4.6,
    reviewCount: 61,
    description:
      "Mixed case of collectible Poké Ball tins (24 per case, assorted styles). Each contains sealed boosters — a strong checkout-counter SKU.",
  },
  {
    id: "sleeved-sv-blister",
    slug: "sleeved-booster-blister-case",
    name: "Sleeved Booster Blisters — Case (144ct)",
    category: "sleeved-boosters",
    set: "Scarlet & Violet",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-SB-BL-144",
    caseQty: "144 sleeved packs / case",
    moq: 1,
    availability: "in-stock",
    stock: 288,
    art: { from: "#1e3a8a", to: "#60a5fa", emoji: "✨" },
    authentic: true,
    popularity: 68,
    rating: 4.5,
    reviewCount: 44,
    description:
      "Case of sleeved booster blisters (144 packs). Retail-ready, hangable packaging — ideal for shelf and rack placement.",
  },
  {
    id: "bnb-sv-kit",
    slug: "build-and-battle-kit-case",
    name: "Build & Battle Kit — Case",
    category: "build-battle",
    set: "Scarlet & Violet",
    brand: "Scarlet & Violet",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-BNB-SV-EN",
    caseQty: "10 kits / case",
    moq: 1,
    availability: "pre-order",
    stock: 40,
    art: { from: "#0f766e", to: "#2dd4bf", emoji: "⚔️" },
    authentic: true,
    isPreOrder: true,
    popularity: 70,
    rating: 4.7,
    reviewCount: 22,
    description:
      "Prerelease Build & Battle kit case (10 per case). Great for events and league support. Pre-order now for next-wave allocation.",
  },
  {
    id: "graded-charizard-psa10",
    slug: "charizard-ex-psa-10-lot",
    name: "Charizard ex — PSA 10 Gem Mint (Dealer Lot)",
    category: "graded",
    set: "Obsidian Flames",
    brand: "Graded",
    language: "English",
    rarity: "Ultra Rare",
    condition: null,
    sku: "RDX-GR-CHZ-P10",
    caseQty: "5 slabs / lot",
    moq: 1,
    availability: "low-stock",
    stock: 15,
    art: { from: "#7f1d1d", to: "#ef4444", emoji: "🐉" },
    authentic: true,
    grading: { company: "PSA", grade: 10, certNumber: "PSA-84920117" },
    isBestSeller: true,
    popularity: 98,
    rating: 5.0,
    reviewCount: 41,
    description:
      "Dealer lot of PSA 10 Gem Mint Charizard ex slabs (5 per lot). Cert numbers verifiable on the PSA population report. Ships foam-lined and fully insured.",
  },
  {
    id: "graded-mixed-psa9",
    slug: "graded-slab-mixed-lot-psa9",
    name: "Graded Slabs — Mixed PSA 9/10 Dealer Lot (25ct)",
    category: "graded",
    set: "Mixed Modern Sets",
    brand: "Graded",
    language: "English",
    rarity: "Ultra Rare",
    condition: null,
    sku: "RDX-GR-MIX-25",
    caseQty: "25 slabs / lot",
    moq: 1,
    availability: "in-stock",
    stock: 8,
    art: { from: "#854d0e", to: "#fde047", emoji: "🏆" },
    authentic: true,
    grading: { company: "PSA", grade: 9, certNumber: "PSA-MIXED-LOT" },
    popularity: 83,
    rating: 4.8,
    reviewCount: 27,
    description:
      "Curated 25-slab lot of PSA 9/10 modern chase cards. Each cert verifiable; full manifest provided on quote. A ready-made graded case for shops.",
  },
  {
    id: "singles-holo-500",
    slug: "holo-rares-bulk-lot-500",
    name: "Holo Rares — Sorted Bulk Lot (500ct)",
    category: "singles",
    set: "Mixed Modern Sets",
    brand: "Mixed",
    language: "English",
    rarity: "Holo Rare",
    condition: "NM",
    sku: "RDX-SG-HOLO-500",
    caseQty: "500 cards / lot",
    moq: 1,
    availability: "in-stock",
    stock: 40,
    art: { from: "#1e3a8a", to: "#60a5fa", emoji: "🃏" },
    authentic: true,
    popularity: 78,
    rating: 4.7,
    reviewCount: 61,
    description:
      "Sorted 500-count bulk lot of Near Mint holo rares from assorted modern sets. Machine-counted and hand-verified. Pallet quantities available on request.",
  },
  {
    id: "singles-common-5000",
    slug: "commons-uncommons-bulk-brick-5000",
    name: "Commons & Uncommons — Bulk Brick (5,000ct)",
    category: "singles",
    set: "Mixed Modern Sets",
    brand: "Mixed",
    language: "English",
    rarity: "Common",
    condition: "NM",
    sku: "RDX-SG-CU-5000",
    caseQty: "5,000 cards / brick",
    moq: 1,
    availability: "in-stock",
    stock: 60,
    art: { from: "#374151", to: "#9ca3af", emoji: "📦" },
    authentic: true,
    popularity: 62,
    rating: 4.5,
    reviewCount: 88,
    description:
      "Five-thousand-count bulk brick of Near Mint commons and uncommons. Ideal for deck-builders, kids' packs, and collection starters. Priced by the thousand at volume.",
  },
  {
    id: "jp-booster-box-case",
    slug: "japanese-booster-box-case",
    name: "Japanese Booster Box — Sealed Case (Direct Import)",
    category: "japanese",
    set: "Japanese — Latest Wave",
    brand: "Japanese",
    language: "Japanese",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-JP-BB-CASE",
    caseQty: "12 boxes / case",
    moq: 1,
    availability: "in-stock",
    stock: 96,
    art: { from: "#581c87", to: "#c084fc", emoji: "🎌" },
    authentic: true,
    isBestSeller: true,
    popularity: 90,
    rating: 4.9,
    reviewCount: 73,
    description:
      "Direct-from-Japan sealed booster box case (12 per case). Sourced through verified Japanese distribution. Strong margins and high collector demand overseas.",
  },
  {
    id: "jp-vstar-case",
    slug: "japanese-special-set-case",
    name: "Japanese High-Class Set — Sealed Case",
    category: "japanese",
    set: "Japanese — High Class",
    brand: "Japanese",
    language: "Japanese",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-JP-HC-CASE",
    caseQty: "20 boxes / case",
    moq: 1,
    availability: "pre-order",
    stock: 40,
    art: { from: "#701a75", to: "#e879f9", emoji: "🎴" },
    authentic: true,
    isPreOrder: true,
    popularity: 86,
    rating: 4.9,
    reviewCount: 31,
    description:
      "High-class Japanese set case (20 boxes). Premium print quality and sought-after alt arts. Pre-order allocation open for the next release wave.",
  },
  {
    id: "acc-toploaders-case",
    slug: "premium-toploaders-wholesale-case",
    name: "Premium Toploaders — Wholesale Case (1,000ct)",
    category: "accessories",
    set: "RareDex Supplies",
    brand: "Supplies",
    language: "N/A",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-AC-TL-1000",
    caseQty: "1,000 toploaders / case",
    moq: 1,
    availability: "in-stock",
    stock: 300,
    art: { from: "#0f172a", to: "#38bdf8", emoji: "🛡️" },
    authentic: true,
    popularity: 60,
    rating: 4.8,
    reviewCount: 130,
    description:
      "Case of 1,000 rigid 35pt toploaders. Crystal clear, no-tack surface. A core consumable for any card shop or online seller.",
  },
  {
    id: "acc-sleeves-case",
    slug: "matte-sleeves-wholesale-case",
    name: "Matte Card Sleeves — Wholesale Case (5,000ct)",
    category: "accessories",
    set: "RareDex Supplies",
    brand: "Supplies",
    language: "N/A",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-AC-SL-5000",
    caseQty: "5,000 sleeves / case",
    moq: 1,
    availability: "in-stock",
    stock: 250,
    art: { from: "#134e4a", to: "#2dd4bf", emoji: "🗂️" },
    authentic: true,
    isNew: true,
    popularity: 58,
    rating: 4.7,
    reviewCount: 102,
    description:
      "Case of 5,000 standard-size matte sleeves (50 packs of 100). Smooth shuffle feel, archival-safe material. High-velocity accessory line.",
  },
  {
    id: "mystery-repack-case",
    slug: "mystery-repack-box-case",
    name: "Mystery Repack Box — Case (24ct)",
    category: "mystery",
    set: "Curated Mix",
    brand: "Mixed",
    language: "Mixed",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-MY-RP-24",
    caseQty: "24 repacks / case",
    moq: 1,
    availability: "in-stock",
    stock: 120,
    art: { from: "#1e1b4b", to: "#6366f1", emoji: "🎁" },
    authentic: true,
    isBestSeller: true,
    popularity: 80,
    rating: 4.6,
    reviewCount: 45,
    description:
      "Case of curated mystery repack boxes (24 per case) — each blends authentic packs, singles, and a chance at graded hits. A proven high-turn impulse product.",
  },
  {
    id: "mystery-hit-lot",
    slug: "guaranteed-hit-mystery-lot",
    name: "Guaranteed Hit Mystery Lot — Bulk (50ct)",
    category: "mystery",
    set: "Curated Mix",
    brand: "Mixed",
    language: "Mixed",
    rarity: "Ultra Rare",
    condition: null,
    sku: "RDX-MY-HIT-50",
    caseQty: "50 packs / lot",
    moq: 1,
    availability: "low-stock",
    stock: 18,
    art: { from: "#4a044e", to: "#d946ef", emoji: "💎" },
    authentic: true,
    popularity: 76,
    rating: 4.7,
    reviewCount: 33,
    description:
      "Bulk lot of 50 guaranteed-hit mystery packs, each containing at least one ultra rare or better. Great for live breakers and mystery-box operators.",
  },
  {
    id: "clearance-swsh-box",
    slug: "clearance-sword-shield-booster-box-case",
    name: "Sword & Shield Booster Box — Clearance Case",
    category: "clearance",
    set: "Sword & Shield",
    brand: "Sword & Shield",
    language: "English",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-CL-SWSH-BB",
    caseQty: "6 boxes / case",
    moq: 1,
    availability: "in-stock",
    stock: 54,
    art: { from: "#312e81", to: "#818cf8", emoji: "🏷️" },
    authentic: true,
    isClearance: true,
    popularity: 64,
    rating: 4.6,
    reviewCount: 57,
    description:
      "Overstock clearance case of Sword & Shield era booster boxes. Fully authentic sealed product at closeout wholesale pricing — while stock lasts.",
  },
  {
    id: "clearance-accessory-mix",
    slug: "clearance-accessory-mixed-pallet",
    name: "Accessory Mixed Pallet — Clearance",
    category: "clearance",
    set: "RareDex Supplies",
    brand: "Supplies",
    language: "N/A",
    rarity: "Sealed",
    condition: null,
    sku: "RDX-CL-ACC-PLT",
    caseQty: "1 mixed pallet",
    moq: 1,
    availability: "low-stock",
    stock: 6,
    art: { from: "#164e63", to: "#22d3ee", emoji: "🏷️" },
    authentic: true,
    isClearance: true,
    popularity: 55,
    rating: 4.5,
    reviewCount: 19,
    description:
      "Mixed clearance pallet of sleeves, toploaders, deck boxes, and binders. Assorted quantities at closeout pricing — full manifest on quote.",
  },
];

// ---- Pricing ----
// Per-unit USD price keyed by product id. Kept separate from the catalog data
// so pricing can move to the backend cleanly. Used by the cart & checkout.
const PRICES: Record<string, number> = {
  "bb-sv-obsidian": 549,
  "bb-sv-paldea": 519,
  "etb-sv-paradox": 349,
  "etb-sv-temporal": 335,
  "pack-obsidian-display": 129,
  "prem-sv-upc": 289,
  "colbox-sv-charizard": 219,
  "tin-sv-poke-ball": 159,
  "sleeved-sv-blister": 189,
  "bnb-sv-kit": 199,
  "graded-charizard-psa10": 2499,
  "graded-mixed-psa9": 1899,
  "singles-holo-500": 349,
  "singles-common-5000": 199,
  "jp-booster-box-case": 899,
  "jp-vstar-case": 1299,
  "acc-toploaders-case": 89,
  "acc-sleeves-case": 129,
  "mystery-repack-case": 399,
  "mystery-hit-lot": 299,
  "clearance-swsh-box": 449,
  "clearance-accessory-mix": 149,
};

export function priceOf(product: Product): number {
  return PRICES[product.id] ?? 99;
}

// ---- Lookup & query helpers (drop-in replaceable by API calls later) ----

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeatured(limit = 8): Product[] {
  return [...products].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}

export function getBestSellers(limit = 8): Product[] {
  return products.filter((p) => p.isBestSeller).slice(0, limit);
}

export function getNewArrivals(limit = 8): Product[] {
  return products.filter((p) => p.isNew || p.isPreOrder).slice(0, limit);
}

export function getClearance(limit = 8): Product[] {
  return products.filter((p) => p.isClearance).slice(0, limit);
}

export function getRelated(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .concat(products.filter((p) => p.id !== product.id && p.category !== product.category))
    .slice(0, limit);
}

export function allSets(): string[] {
  return Array.from(new Set(products.map((p) => p.set))).sort();
}

export function allBrands(): string[] {
  return Array.from(new Set(products.map((p) => p.brand))).sort();
}

export function allLanguages(): string[] {
  return Array.from(new Set(products.map((p) => p.language))).sort();
}
